In [42]:
%load_ext autoreload
%autoreload 2
import spectrum_fundamentals
import spectrum_io
import oktoberfest

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [54]:
#plink2
import subprocess

command = "python /home/mkalhor/wilhelmlab/oktoberfest/oktoberfest/run_oktoberfest.py --search_dir /home/mkalhor/wilhelmlab/notebooks/notebooks --config_path /home/mkalhor/wilhelmlab/notebooks/notebooks/config.json"
subprocess.run(command, shell=True)

2023-07-09 19:57:56,635 - INFO - oktoberfest::main Oktoberfest version 0.3.0
Copyright (c) 2020-2021 Oktoberfest dev-team. All rights reserved.
Written by
- Wassim Gabriel (wassim.gabriel@tum.de),
- Ludwig Lautenbacher (ludwig.lautenbacher@tum.de),
- Matthew The (matthew.the@tum.de),
- Mario Picciani (mario.picciani@in.tum.de),
- Firas Hamood (firas.hamood@tum.de),
- Cecilia Jensen (cecilia.jensen@tum.de)
at the Technical University of Munich.
2023-07-09 19:57:56,635 - INFO - oktoberfest::main Issued command: run_oktoberfest.py --search_dir /home/mkalhor/wilhelmlab/notebooks/notebooks --config_path /home/mkalhor/wilhelmlab/notebooks/notebooks/config.json
test
/home/mkalhor/wilhelmlab/notebooks/notebooks
2023-07-09 19:57:56,637 - INFO - oktoberfest.utils.config::read Reading configuration from /home/mkalhor/wilhelmlab/notebooks/notebooks/config.json
2023-07-09 19:57:56,639 - INFO - oktoberfest.utils.config::read Reading configuration from /home/mkalhor/wilhelmlab/notebooks/notebooks/config.json
2023-07-09 19:57:56,639 - INFO - oktoberfest.ce_calibration::_load_search search_type is plink2
2023-07-09 19:57:56,639 - INFO - oktoberfest.ce_calibration::_gen_internal_search_result_from_msms Converting msms data at /home/mkalhor/wilhelmlab/notebooks/notebooks/msms.csv to internal search result.
2023-07-09 19:57:56,639 - INFO - spectrum_io.search_result.search_results::generate_internal Found search results in internal format at /home/mkalhor/wilhelmlab/notebooks/notebooks/msms.prosit, skipping conversion
2023-07-09 19:57:56,651 - INFO - oktoberfest.ce_calibration::perform_alignment Path to hdf5 file with annotations for /home/mkalhor/wilhelmlab/notebooks/notebooks: /home/mkalhor/wilhelmlab/notebooks/notebooks/mzML/Lumos_RSLC8_steppedHCD_SEC_F2.mzML.hdf5
2023-07-09 19:57:56,717 - INFO - spectrum_io.file.hdf5::read_file Reading sparse matrix from hdf5 file. Available keys: <KeysViewHDF5 ['meta_data', 'sparse_raw_intensity', 'sparse_raw_mz']>
2023-07-09 19:57:56,794 - INFO - spectrum_io.file.hdf5::read_file Reading sparse matrix from hdf5 file. Available keys: <KeysViewHDF5 ['meta_data', 'sparse_raw_intensity', 'sparse_raw_mz']>

/home/mkalhor/wilhelmlab/oktoberfest/oktoberfest/ce_calibration.py:152: FutureWarning: The behavior of .astype from SparseDtype to a non-sparse dtype is deprecated. In a future version, this will return a non-sparse array with the requested dtype. To retain the old behavior, use `obj.astype(SparseDtype(dtype))`
  self.alignment_library.spectra_data.to_csv("/home/mkalhor/wilhelmlab/notebooks/notebooks/alignment_library.csv")
Traceback (most recent call last):
  File "/home/mkalhor/wilhelmlab/oktoberfest/oktoberfest/run_oktoberfest.py", line 41, in <module>
    main()
  File "/home/mkalhor/wilhelmlab/oktoberfest/oktoberfest/run_oktoberfest.py", line 37, in main
    runner.run_job(args.search_dir, args.config_path)
  File "/home/mkalhor/wilhelmlab/oktoberfest/oktoberfest/runner.py", line 208, in run_job
    run_ce_calibration(msms_path, search_dir, config_path, glob_pattern)
  File "/home/mkalhor/wilhelmlab/oktoberfest/oktoberfest/runner.py", line 142, in run_ce_calibration
    ce_calib.perform_alignment(ce_calib._load_search())
  File "/home/mkalhor/wilhelmlab/oktoberfest/oktoberfest/ce_calibration.py", line 212, in perform_alignment
    self.grpc_predict(self.alignment_library, alignment=True)  # predict alignment
  File "/home/mkalhor/wilhelmlab/oktoberfest/oktoberfest/spectral_library.py", line 216, in grpc_predict
    intensity_predictions = infer_predictions(
  File "/home/mkalhor/wilhelmlab/oktoberfest/oktoberfest/spectral_library.py", line 56, in infer_predictions
    prediction = triton_client.infer(model, inputs=infer_inputs, outputs=infer_outputs)
  File "/home/mkalhor/anaconda3/envs/oktoberfest/lib/python3.10/site-packages/tritonclient/grpc/_client.py", line 1321, in infer
    raise_error_grpc(rpc_error)
  File "/home/mkalhor/anaconda3/envs/oktoberfest/lib/python3.10/site-packages/tritonclient/grpc/_utils.py", line 62, in raise_error_grpc
    raise get_error_grpc(rpc_error) from None
tritonclient.utils.InferenceServerException: [StatusCode.UNAVAILABLE] failed to connect to all addresses; last error: UNKNOWN: ipv4:10.157.98.13:8505: Failed to connect to remote host: FD Shutdown

CompletedProcess(args='python /home/mkalhor/wilhelmlab/oktoberfest/oktoberfest/run_oktoberfest.py --search_dir /home/mkalhor/wilhelmlab/notebooks/notebooks --config_path /home/mkalhor/wilhelmlab/notebooks/notebooks/config.json', returncode=1)

In [6]:
#maxquant
import subprocess

command = "python /home/mkalhor/wilhelmlab/oktoberfest/oktoberfest/run_oktoberfest.py --search_dir /home/mkalhor/wilhelmlab/oktoberfest/data/plasma --config_path /home/mkalhor/wilhelmlab/oktoberfest/data/plasma/config.json"
subprocess.run(command, shell=True)

2023-07-07 14:51:58,654 - INFO - oktoberfest::main Oktoberfest version 0.3.0
Copyright (c) 2020-2021 Oktoberfest dev-team. All rights reserved.
Written by
- Wassim Gabriel (wassim.gabriel@tum.de),
- Ludwig Lautenbacher (ludwig.lautenbacher@tum.de),
- Matthew The (matthew.the@tum.de),
- Mario Picciani (mario.picciani@in.tum.de),
- Firas Hamood (firas.hamood@tum.de),
- Cecilia Jensen (cecilia.jensen@tum.de)
at the Technical University of Munich.
2023-07-07 14:51:58,654 - INFO - oktoberfest::main Issued command: run_oktoberfest.py --search_dir /home/mkalhor/wilhelmlab/oktoberfest/data/plasma --config_path /home/mkalhor/wilhelmlab/oktoberfest/data/plasma/config.json
test
/home/mkalhor/wilhelmlab/oktoberfest/data/plasma
2023-07-07 14:51:58,655 - INFO - oktoberfest.utils.config::read Reading configuration from /home/mkalhor/wilhelmlab/oktoberfest/data/plasma/config.json
2023-07-07 14:51:58,657 - INFO - oktoberfest.utils.config::read Reading configuration from /home/mkalhor/wilhelmlab/oktoberfest/data/plasma/config.json
2023-07-07 14:51:58,658 - INFO - oktoberfest.ce_calibration::_load_search search_type is maxquant
2023-07-07 14:51:58,658 - INFO - oktoberfest.ce_calibration::_gen_internal_search_result_from_msms Converting msms data at /home/mkalhor/wilhelmlab/oktoberfest/data/plasma/msms.txt to internal search result.
2023-07-07 14:51:58,658 - INFO - spectrum_io.search_result.search_results::generate_internal Found search results in internal format at /home/mkalhor/wilhelmlab/oktoberfest/data/plasma/msms.prosit, skipping conversion
2023-07-07 14:51:58,680 - INFO - oktoberfest.ce_calibration::perform_alignment Path to hdf5 file with annotations for /home/mkalhor/wilhelmlab/oktoberfest/data/plasma: /home/mkalhor/wilhelmlab/oktoberfest/data/plasma/mzML/Plamsa_03401_RD2_30min_Top10_86ms_RP13_R1.mzML.hdf5
2023-07-07 14:51:58,680 - INFO - oktoberfest.ce_calibration::_load_rawfile raw_type is thermo
2023-07-07 14:51:58,680 - INFO - oktoberfest.ce_calibration::_gen_mzml_from_thermo Converting thermo rawfile to mzml.
2023-07-07 14:51:58,681 - INFO - spectrum_io.raw.thermo_raw::convert_raw_mzml Found converted file at /home/mkalhor/wilhelmlab/oktoberfest/data/plasma/mzML/Plamsa_03401_RD2_30min_Top10_86ms_RP13_R1.mzML, skipping conversion
2023-07-07 14:51:58,682 - INFO - spectrum_io.raw.msraw::read_mzml Reading mzML file: /home/mkalhor/wilhelmlab/oktoberfest/data/plasma/mzML/Plamsa_03401_RD2_30min_Top10_86ms_RP13_R1.mzML
2023-07-07 14:52:21,731 - INFO - oktoberfest.ce_calibration::merge_mzml_and_msms Merging rawfile and search result
2023-07-07 14:52:21,752 - INFO - oktoberfest.ce_calibration::merge_mzml_and_msms There are 6875 matched identifications
2023-07-07 14:52:21,753 - INFO - oktoberfest.ce_calibration::merge_mzml_and_msms Annotating raw spectra
2023-07-07 12:53:32,244 - INFO - spectrum_fundamentals.annotation.annotation::annotate_spectra Removed count    6875.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
Name: removed_peaks, dtype: float64 redundant peaks
2023-07-07 14:53:32,252 - INFO - oktoberfest.ce_calibration::merge_mzml_and_msms Preparing library
2023-07-07 14:53:33,299 - INFO - spectrum_io.file.hdf5::write_dataset Data written to /home/mkalhor/wilhelmlab/oktoberfest/data/plasma/mzML/Plamsa_03401_RD2_30min_Top10_86ms_RP13_R1.mzML.hdf5

/home/mkalhor/wilhelmlab/oktoberfest/oktoberfest/ce_calibration.py:152: FutureWarning: The behavior of .astype from SparseDtype to a non-sparse dtype is deprecated. In a future version, this will return a non-sparse array with the requested dtype. To retain the old behavior, use `obj.astype(SparseDtype(dtype))`
  self.alignment_library.spectra_data.to_csv("/home/mkalhor/wilhelmlab/oktoberfest/data/plasma/alignment_library.csv")

2023-07-07 14:53:33,546 - INFO - spectrum_io.file.hdf5::write_dataset Data appended to /home/mkalhor/wilhelmlab/oktoberfest/data/plasma/mzML/Plamsa_03401_RD2_30min_Top10_86ms_RP13_R1.mzML.hdf5
2023-07-07 14:53:33,782 - INFO - spectrum_io.file.hdf5::write_dataset Data appended to /home/mkalhor/wilhelmlab/oktoberfest/data/plasma/mzML/Plamsa_03401_RD2_30min_Top10_86ms_RP13_R1.mzML.hdf5

/home/mkalhor/wilhelmlab/oktoberfest/oktoberfest/ce_calibration.py:181: FutureWarning: The behavior of .astype from SparseDtype to a non-sparse dtype is deprecated. In a future version, this will return a non-sparse array with the requested dtype. To retain the old behavior, use `obj.astype(SparseDtype(dtype))`
  self.alignment_library.spectra_data.to_csv(self.results_path / "SA.tsv", sep="\t")

CompletedProcess(args='python /home/mkalhor/wilhelmlab/oktoberfest/oktoberfest/run_oktoberfest.py --search_dir /home/mkalhor/wilhelmlab/oktoberfest/data/plasma --config_path /home/mkalhor/wilhelmlab/oktoberfest/data/plasma/config.json', returncode=0)

In [33]:
#maxquant
import pandas as pd 
import pandas as pd
pd.set_option('display.max_columns', 368)
pd.set_option('display.max_rows', 10)

df_join = pd.read_csv("/home/mkalhor/wilhelmlab/oktoberfest/data/plasma/df_join.csv")
df_raw = pd.read_csv("/home/mkalhor/wilhelmlab/oktoberfest/data/plasma/df_raw.csv")
df_search = pd.read_csv("/home/mkalhor/wilhelmlab/oktoberfest/data/plasma/df_search.csv")
df_alignment_library = pd.read_csv("/home/mkalhor/wilhelmlab/oktoberfest/data/plasma/alignment_library.csv")

#display(df_raw)
#display(df_search.columns)
#display(df_search)
#display(df_join.columns)
#display(df_join["REVERSE"])
display(df_join)
display(len(df_join["INTENSITIES"][1]))
display(df_join["MZ"][0])
#display(df_alignment_library.head(10))
#print(df_alignment_library.columns)

,Unnamed: 0,RAW_FILE,SCAN_NUMBER,MODIFIED_SEQUENCE,PRECURSOR_CHARGE,SCAN_EVENT_NUMBER,MASS,SCORE,REVERSE,SEQUENCE,PEPTIDE_LENGTH,INTENSITIES,MZ,MZ_RANGE,RETENTION_TIME,MASS_ANALYZER,FRAGMENTATION
0,0,Plamsa_03401_RD2_30min_Top10_86ms_RP13_R1,917,AAAATVEEPQVGIVGR,3,5,1566.83660,3.4214,True,AAAATVEEPQVGIVGR,16,[ 3330.6796875 1934.03735352 2320.14038086 ...,[110.07154083 129.10241699 144.55168152 175.11...,100.0000-1085.0000,1.977529,FTMS,HCD
1,1,Plamsa_03401_RD2_30min_Top10_86ms_RP13_R1,9832,AAC[UNIMOD:4]GPSSC[UNIMOD:4]YALFPR,2,7,1555.69120,163.6400,False,AACGPSSCYALFPR,14,[ 3006.35424805 3133.74047852 6092.626953...,[ 102.05517578 104.05295563 110.07146454 11...,100.0000-1610.0000,16.250146,FTMS,HCD
2,2,Plamsa_03401_RD2_30min_Top10_86ms_RP13_R1,4680,AAC[UNIMOD:4]LLPK,2,3,771.43130,91.0930,False,AACLLPK,7,[104229.5859375 14248.17773438 5132.610351...,[101.07134247 101.10778809 110.07145691 115.08...,100.0000-810.0000,7.936037,FTMS,HCD
3,3,Plamsa_03401_RD2_30min_Top10_86ms_RP13_R1,2418,AAC[UNIMOD:4]LRRC[UNIMOD:4]K,2,4,1033.52730,17.2700,False,AACLRRCK,8,[ 21385.64648438 115806.5625 12452.429687...,[ 102.00144196 110.07165527 111.05552673 11...,100.0000-1075.0000,4.307089,FTMS,HCD
4,4,Plamsa_03401_RD2_30min_Top10_86ms_RP13_R1,9044,AAC[UNIMOD:4]LRRC[UNIMOD:4]K,2,8,1033.52730,8.1535,False,AACLRRCK,8,[20340.95507812 5900.65966797 3886.17651367 ...,[ 110.0716629 115.08719635 116.01708221 12...,100.0000-1605.0000,15.004058,FTMS,HCD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6870,6870,Plamsa_03401_RD2_30min_Top10_86ms_RP13_R1,14120,KPSPQEVSELQATYRLLR,3,2,2114.14840,4.4385,False,KPSPQEVSELQATYRLLR,18,[ 2461.81933594 7236.71777344 10561.179687...,[ 100.61367798 102.05549622 104.05323029 11...,100.0000-2180.0000,23.249262,FTMS,HCD
6871,6871,Plamsa_03401_RD2_30min_Top10_86ms_RP13_R1,7471,KPSYHGYNQMMEC[UNIMOD:4]LPGYK,3,6,2201.96970,84.8290,False,KPSYHGYNQMMECLPGYK,18,[ 13183.55371094 4750.57910156 20528.392578...,[ 101.07139587 101.10778046 104.05337524 11...,100.0000-2270.0000,12.517024,FTMS,HCD
6872,6872,Plamsa_03401_RD2_30min_Top10_86ms_RP13_R1,7505,KPSYHGYNQMMEC[UNIMOD:4]LPGYK,3,7,2201.96970,110.0400,False,KPSYHGYNQMMECLPGYK,18,[ 9321.30566406 4817.20166016 20059.384765...,[ 101.07161713 101.10862732 104.05318451 11...,100.0000-2270.0000,12.565900,FTMS,HCD
6873,6873,Plamsa_03401_RD2_30min_Top10_86ms_RP13_R1,1300,KPVDEYK,2,2,877.45453,61.9620,False,KPVDEYK,7,[ 9595.16796875 30576.3203125 6821.15966797 ...,[110.0714798 129.10238647 130.08604431 136.07...,100.0000-915.0000,2.644147,FTMS,HCD
6874,6874,Plamsa_03401_RD2_30min_Top10_86ms_RP13_R1,4777,KPVDEYKDC[UNIMOD:4]HLAQVPSHTVVAR,5,6,2548.28560,71.1480,False,KPVDEYKDCHLAQVPSHTVVAR,22,[ 7664.32226562 3087.22241211 4576.088867...,[ 101.07139587 101.10804749 102.05547333 11...,100.0000-2625.0000,8.093063,FTMS,HCD

1742

'[110.07154083 129.10241699 144.55168152 175.11956787 214.11827087\n 224.05545044 237.45191956 242.19226074 244.90187073 310.17642212\n 364.82260132 366.81613159 382.83084106 383.83081055 384.82580566\n 384.88635254 398.64212036 402.85897827 411.62173462 443.84609985\n 444.84924316 445.84619141 462.87042236 463.18185425 463.85922241\n 523.26763916 948.35113525]'

In [46]:
#plink2

import pandas as pd 
pd.set_option('display.max_columns', 370)
pd.set_option('display.max_rows', 10)




df_join = pd.read_csv("/home/mkalhor/wilhelmlab/notebooks/notebooks/df_join.csv")
df_raw = pd.read_csv("/home/mkalhor/wilhelmlab/notebooks/notebooks/df_raw.csv")
df_search = pd.read_csv("/home/mkalhor/wilhelmlab/notebooks/notebooks/df_search.csv")
df_alignment_library = pd.read_csv("/home/mkalhor/wilhelmlab/notebooks/notebooks/alignment_library.csv")

#display(df_raw)
#display(df_search.columns)
#display(df_search)
#display(df_join.columns)
#display(df_join["REVERSE"])
#display(df_join)
display(df_alignment_library)
#display(df_alignment_library.head(10))
#display(df_alignment_library.tail(10))

,Unnamed: 0,RAW_FILE,PRECURSOR_CHARGE,MASS,Peptide,CROSSLINKER_TYPE,SCORE,REVERSE,SCAN_NUMBER,SEQUENCE_A,SEQUENCE_B,CROSSLINKER_POSITION_A,CROSSLINKER_POSITION_B,PEPTIDE_LENGTH_A,PEPTIDE_LENGTH_B,MODIFIED_SEQUENCE_A,MODIFIED_SEQUENCE_B,MZ_RANGE,RETENTION_TIME,MASS_ANALYZER,FRAGMENTATION,INTENSITY_RAW_Y1+,INTENSITY_RAW_Y1++,INTENSITY_RAW_Y1+++,INTENSITY_RAW_B1+,INTENSITY_RAW_B1++,INTENSITY_RAW_B1+++,INTENSITY_RAW_Y2+,INTENSITY_RAW_Y2++,INTENSITY_RAW_Y2+++,INTENSITY_RAW_B2+,INTENSITY_RAW_B2++,INTENSITY_RAW_B2+++,INTENSITY_RAW_Y3+,INTENSITY_RAW_Y3++,INTENSITY_RAW_Y3+++,INTENSITY_RAW_B3+,INTENSITY_RAW_B3++,INTENSITY_RAW_B3+++,INTENSITY_RAW_Y4+,INTENSITY_RAW_Y4++,INTENSITY_RAW_Y4+++,INTENSITY_RAW_B4+,INTENSITY_RAW_B4++,INTENSITY_RAW_B4+++,INTENSITY_RAW_Y5+,INTENSITY_RAW_Y5++,INTENSITY_RAW_Y5+++,INTENSITY_RAW_B5+,INTENSITY_RAW_B5++,INTENSITY_RAW_B5+++,INTENSITY_RAW_Y6+,INTENSITY_RAW_Y6++,INTENSITY_RAW_Y6+++,INTENSITY_RAW_B6+,INTENSITY_RAW_B6++,INTENSITY_RAW_B6+++,INTENSITY_RAW_Y7+,INTENSITY_RAW_Y7++,INTENSITY_RAW_Y7+++,INTENSITY_RAW_B7+,INTENSITY_RAW_B7++,INTENSITY_RAW_B7+++,INTENSITY_RAW_Y8+,INTENSITY_RAW_Y8++,INTENSITY_RAW_Y8+++,INTENSITY_RAW_B8+,INTENSITY_RAW_B8++,INTENSITY_RAW_B8+++,INTENSITY_RAW_Y9+,INTENSITY_RAW_Y9++,INTENSITY_RAW_Y9+++,INTENSITY_RAW_B9+,INTENSITY_RAW_B9++,INTENSITY_RAW_B9+++,INTENSITY_RAW_Y10+,INTENSITY_RAW_Y10++,INTENSITY_RAW_Y10+++,INTENSITY_RAW_B10+,INTENSITY_RAW_B10++,INTENSITY_RAW_B10+++,INTENSITY_RAW_Y11+,INTENSITY_RAW_Y11++,INTENSITY_RAW_Y11+++,INTENSITY_RAW_B11+,INTENSITY_RAW_B11++,INTENSITY_RAW_B11+++,INTENSITY_RAW_Y12+,INTENSITY_RAW_Y12++,INTENSITY_RAW_Y12+++,INTENSITY_RAW_B12+,INTENSITY_RAW_B12++,INTENSITY_RAW_B12+++,INTENSITY_RAW_Y13+,INTENSITY_RAW_Y13++,INTENSITY_RAW_Y13+++,INTENSITY_RAW_B13+,INTENSITY_RAW_B13++,INTENSITY_RAW_B13+++,INTENSITY_RAW_Y14+,INTENSITY_RAW_Y14++,INTENSITY_RAW_Y14+++,INTENSITY_RAW_B14+,INTENSITY_RAW_B14++,INTENSITY_RAW_B14+++,INTENSITY_RAW_Y15+,INTENSITY_RAW_Y15++,INTENSITY_RAW_Y15+++,INTENSITY_RAW_B15+,INTENSITY_RAW_B15++,INTENSITY_RAW_B15+++,INTENSITY_RAW_Y16+,INTENSITY_RAW_Y16++,INTENSITY_RAW_Y16+++,INTENSITY_RAW_B16+,INTENSITY_RAW_B16++,INTENSITY_RAW_B16+++,INTENSITY_RAW_Y17+,INTENSITY_RAW_Y17++,INTENSITY_RAW_Y17+++,INTENSITY_RAW_B17+,INTENSITY_RAW_B17++,INTENSITY_RAW_B17+++,INTENSITY_RAW_Y18+,INTENSITY_RAW_Y18++,INTENSITY_RAW_Y18+++,INTENSITY_RAW_B18+,INTENSITY_RAW_B18++,INTENSITY_RAW_B18+++,INTENSITY_RAW_Y19+,INTENSITY_RAW_Y19++,INTENSITY_RAW_Y19+++,INTENSITY_RAW_B19+,INTENSITY_RAW_B19++,INTENSITY_RAW_B19+++,INTENSITY_RAW_Y20+,INTENSITY_RAW_Y20++,INTENSITY_RAW_Y20+++,INTENSITY_RAW_B20+,INTENSITY_RAW_B20++,INTENSITY_RAW_B20+++,INTENSITY_RAW_Y21+,INTENSITY_RAW_Y21++,INTENSITY_RAW_Y21+++,INTENSITY_RAW_B21+,INTENSITY_RAW_B21++,INTENSITY_RAW_B21+++,INTENSITY_RAW_Y22+,INTENSITY_RAW_Y22++,INTENSITY_RAW_Y22+++,INTENSITY_RAW_B22+,INTENSITY_RAW_B22++,INTENSITY_RAW_B22+++,INTENSITY_RAW_Y23+,INTENSITY_RAW_Y23++,INTENSITY_RAW_Y23+++,INTENSITY_RAW_B23+,INTENSITY_RAW_B23++,INTENSITY_RAW_B23+++,INTENSITY_RAW_Y24+,INTENSITY_RAW_Y24++,INTENSITY_RAW_Y24+++,INTENSITY_RAW_B24+,INTENSITY_RAW_B24++,INTENSITY_RAW_B24+++,INTENSITY_RAW_Y25+,INTENSITY_RAW_Y25++,INTENSITY_RAW_Y25+++,INTENSITY_RAW_B25+,INTENSITY_RAW_B25++,INTENSITY_RAW_B25+++,INTENSITY_RAW_Y26+,INTENSITY_RAW_Y26++,INTENSITY_RAW_Y26+++,INTENSITY_RAW_B26+,INTENSITY_RAW_B26++,INTENSITY_RAW_B26+++,INTENSITY_RAW_Y27+,INTENSITY_RAW_Y27++,INTENSITY_RAW_Y27+++,INTENSITY_RAW_B27+,INTENSITY_RAW_B27++,INTENSITY_RAW_B27+++,INTENSITY_RAW_Y28+,INTENSITY_RAW_Y28++,...,MZ_RAW_Y28+++,MZ_RAW_B28+,MZ_RAW_B28++,MZ_RAW_B28+++,MZ_RAW_Y29+,MZ_RAW_Y29++,MZ_RAW_Y29+++,MZ_RAW_B29+,MZ_RAW_B29++,MZ_RAW_B29+++,MZ_RAW_Y30+,MZ_RAW_Y30++,MZ_RAW_Y30+++,MZ_RAW_B30+,MZ_RAW_B30++,MZ_RAW_B30+++,MZ_RAW_Y31+,MZ_RAW_Y31++,MZ_RAW_Y31+++,MZ_RAW_B31+,MZ_RAW_B31++,MZ_RAW_B31+++,MZ_RAW_Y32+,MZ_RAW_Y32++,MZ_RAW_Y32+++,MZ_RAW_B32+,MZ_RAW_B32++,MZ_RAW_B32+++,MZ_RAW_Y33+,MZ_RAW_Y33++,MZ_RAW_Y33+++,MZ_RAW_B33+,MZ_RAW_B33++,MZ_RAW_B33+++,MZ_RAW_Y34+,MZ_RAW_Y34++,MZ_RAW_Y34+++,MZ_RAW_B34+,MZ_RAW_B34++,MZ_RAW_B34+++,MZ_RAW_Y35+,MZ_RAW_Y35++,MZ_RAW_Y35+++,MZ_RAW_B35+,MZ_RAW_B35++,MZ_RAW_B35+++,MZ_RAW_Y36+,MZ_RAW_Y36++,MZ_RAW_Y36+++,MZ_RAW_B36+,MZ_RAW_B36++,MZ_RAW_B36+++,MZ_RAW_Y37+,MZ_RAW_Y37++,MZ_RAW_Y37+++,MZ_RAW_B37+,MZ_RAW_B37++,MZ_RAW_B37+++,MZ_RAW_Y38+,MZ_RAW_Y38++,MZ_RAW_Y38+++,MZ_RAW_B38+,MZ_RAW_B38++,MZ_RAW_B38+++,MZ_RAW_Y39+,MZ_RAW_Y39++,MZ_RAW_Y39+++,MZ_RAW_B39+,MZ_RAW_B39++,MZ_RAW_B39+++,MZ_RAW_Y40+,MZ_RAW_Y40++,MZ_RAW_Y40+++,MZ_RAW_B40+,MZ_RAW_B40++,MZ_RAW_B40+++,MZ_RAW_Y41+,MZ_RAW_Y41++,MZ_RAW_Y41+++,MZ_RAW_B41+,MZ_RAW_B41++,MZ_RAW_B41+++,MZ_RAW_Y42+,MZ_RAW_Y42++,MZ_RAW_Y42+++,MZ_RAW_B42+,MZ_RAW_B42++,MZ_RAW_B42+++,MZ_RAW_Y43+,MZ_RAW_Y43++,MZ_RAW_Y43+++,MZ_RAW_B43+,MZ_RAW_B43++,MZ_RAW_B43+++,MZ_RAW_Y44+,MZ_RAW_Y44++,MZ_RAW_Y44+++,MZ_RAW_B44+,MZ_RAW_B44++,MZ_RAW_B44+++,MZ_RAW_Y45+,MZ_RAW_Y45++,MZ_RAW_Y45+++,MZ_RAW_B45+,MZ_RAW_B45++,MZ_RAW_B45+++,MZ_RAW_Y46+,MZ_RAW_Y46++,MZ_RAW_Y46+++,MZ_RAW_B46+,MZ_RAW_B46++,MZ_RAW_B46+++,MZ_RAW_Y47+,MZ_RAW_Y47++,MZ_RAW_Y47+++,MZ_RAW_B47+,MZ_RAW_B47++,MZ_RAW_B47+++,MZ_RAW_Y48+,MZ_RAW_Y48++,MZ_RAW_Y48+++,MZ_RAW_B48+,MZ_RAW_B48++,MZ_RAW_B48+++,MZ_RAW_Y49+,MZ_RAW_Y49++,MZ_RAW_Y49+++,MZ_RAW_B49+,MZ_RAW_B49++,MZ_RAW_B49+++,MZ_RAW_Y50+,MZ_RAW_Y50++,MZ_RAW_Y50+++,MZ_RAW_B50+,MZ_RAW_B50++,MZ_RAW_B50+++,MZ_RAW_Y51+,MZ_RAW_Y51++,MZ_RAW_Y51+++,MZ_RAW_B51+,MZ_RAW_B51++,MZ_RAW_B51+++,MZ_RAW_Y52+,MZ_RAW_Y52++,MZ_RAW_Y52+++,MZ_RAW_B52+,MZ_RAW_B52++,MZ_RAW_B52+++,MZ_RAW_Y53+,MZ_RAW_Y53++,MZ_RAW_Y53+++,MZ_RAW_B53+,MZ_RAW_B53++,MZ_RAW_B53+++,MZ_RAW_Y54+,MZ_RAW_Y54++,MZ_RAW_Y54+++,MZ_RAW_B54+,MZ_RAW_B54++,MZ_RAW_B54+++,MZ_RAW_Y55+,MZ_RAW_Y55++,MZ_RAW_Y55+++,MZ_RAW_B55+,MZ_RAW_B55++,MZ_RAW_B55+++,MZ_RAW_Y56+,MZ_RAW_Y56++,MZ_RAW_Y56+++,MZ_RAW_B56+,MZ_RAW_B56++,MZ_RAW_B56+++,MZ_RAW_Y57+,MZ_RAW_Y57++,MZ_RAW_Y57+++,MZ_RAW_B57+,MZ_RAW_B57++,MZ_RAW_B57+++,MZ_RAW_Y58+,MZ_RAW_Y58++,MZ_RAW_Y58+++,MZ_RAW_B58+,MZ_RAW_B58++,MZ_RAW_B58+++,CALCULATED_MASS
0,0,Lumos_RSLC8_steppedHCD_SEC_F2,5,4253.060,VEDATLVLSVGDEVEAKFTGVDRK(17)-DEADEKDAIATVNK(6),DSSO,1.408896e-13,False,26371,VEDATLVLSVGDEVEAKFTGVDRK,DEADEKDAIATVNK,17,6,24,14,VEDATLVLSVGDEVEAK[UNIMOD:1896]FTGVDRK,DEADEK[UNIMOD:1896]DAIATVNK,120.0000-2000.0000,81.481894,FTMS,HCD,5.433653e-02,1.000000e-07,0,1.000000e-07,1.000000e-07,0,2.604320e-01,1.000000e-07,0,5.317972e-01,1.000000e-07,0,1.067249e-01,1.000000e-07,0,1.926626e-01,1.000000e-07,0,2.979696e-02,1.000000e-07,0,1.034009e-01,1.000000e-07,0,1.625532e-01,1.000000e-07,0,1.561958e-01,1.000000e-07,0,2.179853e-01,1.000000e-07,0,7.221366e-01,1.000000e-07,0,3.050412e-01,1.795995e-02,0,7.518576e-01,1.284209e-01,0,9.876798e-02,1.282804e-02,0,1.773271e-01,1.789193e-01,0,1.668497e-01,5.791612e-02,0,9.574269e-02,1.675211e-01,0,1.660371e-01,6.423690e-02,0,1.000000e-07,5.462844e-02,0,5.928644e-02,5.999974e-02,0,1.000000e-07,5.280327e-02,0,2.222006e-02,7.748439e-02,0,1.000000e-07,1.000000e-07,0,5.123010e-02,2.345684e-01,0,9.158950e-02,4.709366e-02,0,1.000000e-07,1.000000e+00,0,1.000000e-07,1.000000e-07,0,1.985886e-02,3.276461e-01,0,1.000000e-07,1.000000e-07,0,4.843092e-02,7.073345e-01,0,1.000000e-07,1.000000e-07,0,2.162608e-02,4.117100e-01,0,1.000000e-07,1.000000e-07,0,1.000000e-07,1.972408e-01,0,1.000000e-07,1.000000e-07,0,1.000000e-07,9.207062e-02,0,1.000000e-07,1.000000e-07,0,1.000000e-07,4.255386e-02,0,1.000000e-07,1.000000e-07,0,1.000000e-07,4.044379e-02,0,1.000000e-07,1.478467e-01,0,1.000000e-07,7.526912e-02,0,1.000000e-07,1.000000e-07,0,1.000000e-07,1.000000e-07,0,1.000000e-07,1.000000e-07,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,...,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.0,0.0,0,0.000000e+00,0.000000e+00,0,0.0,0.0,0,0.000000e+00,0.000000e+00,0,0.000000,0.000000e+00,0,0.000000,0.000000e+00,0,0.000000,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,1.036525e+03,1.000000e-07,0,0.000000,0.000000e+00,0,1.107562e+03,5.542863e+02,0,0.000000,0.000000e+00,0,1.236603e+03,6.188044e+02,0,0.000000e+00,0.000000e+00,0,1.335671e+03,6.683398e+02,0,0.000000e+00,0.000000e+00,0,1.464715e+03,7.328607e+02,0,0.000000e+00,0.000000e+00,0,1.579737e+03,7.903743e+02,0,0.000000e+00,0.000000e+00,0,1.636756e+03,8.188843e+02,0,0.000000e+00,0.000000e+00,0,1.735839e+03,8.684178e+02,0,0.000000e+00,0.000000e+00,0,1.822868e+03,9.119348e+02,0,0.000000e+00,0.000000e+00,0,1.000000e-07,9.684775e+02,0,1.000000e-07,9.214449e+02,0,1.000000e-07,1.018012e+03,0,1.000000e-07,1.000000e-07,0,1.000000e-07,1.074554e+03,0,1.000000e-07,1.000000e-07,0,1.000000e-07,1.125075e+03,0,1.000000e-07,1.000000e-07,0,1.000000e-07,1.160599e+03,0,1.000000e-07,1.000000e-07,0,1.000000e-07,1.218109e+03,0,1.000000e-07,1.000000e-07,0,1.000000e-07,1.282622e+03,0,1.000000e-07,1.000000e-07,0,0.000000e+00,1.332160e+03,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,2576.333364
1,1,Lumos_RSLC8_steppedHCD_SEC_F2,5,4289.155,VLESAIANAEHNDGADIDDLKVTK(21)-KVSQALDILTYTNK(1),DSSO,2.034614e-13,False,21289,VLESAIANAEHNDGADIDDLKVTK,KVSQALDILTYTNK,21,1,24,14,VLESAIANAEHNDGADIDDLK[UNIMOD:1896]VTK,K[UNIMOD:1896]VSQALDILTYTNK,120.0000-2000.0000,67.613422,FTMS,HCD,1.194365e-01,1.000000e-07,0,1.000000e-07,1.000000e-07,0,2.547875e-01,1.000000e-07,0,1.000000e+00,1.000000e-07,0,2.105514e-01,1.000000e-07,0,3.155539e-01,1.000000e-07,0,6.017964e-02,1.000000e-07,0,9.141408e-02,1.000000e-07,0,3.797452e-02,1.000000e-07,0,2.613990e-01,1.000000e-07,0,4.103006e-02,1.000000e-07,0,1.317651e-01,1.000000e-07,0,1.061960e-01,1.000000e-07,0,5.070794e-02,1.000000e-07,0,4.922010e-02,1.000000e-07,0,3.219203e-02,1.000000e-07,0,5.865897e-02,1.000000e-07,0,1.000000e-07,1.000000e-07,0,1.000000e-07,1.000000e-07,0,1.000000e-07,1.000000e-07,0,5.376401e-02,1.000000e-07,0,1.000000e-07,1.000000e-07,0,2.558075e-02,1.000000e-07,0,2.075831e-02,1.000000e-07,0,3.371307e-02,1.000000e-07,0,1.000000e-07,2.155658e-02,0,3.213493e-02,3.396769e-02,0,1.000000e-07,2.352497e-02,0,1.000000e-07,1.879605e-02,0,3.135023e-02,5.187476e-02,0,1.000000e-07,2.500085e-02,0,3.523221e-02,1.208224e-01,0,1.000000e-07,7.911550e-02,0,1.000000e-07,1.568761e-01,0,1.000000e-07,2.469279e-01,0,1.000000e-07,1.811680e-02,0,1.000000e-07,2.490412e-01,0,1.000000e-07,3.143046e-02,0,1.000000e-07,6.434399e-02,0,1.000000e-07,2.510708e-02,0,1.000000e-07,2.258121e-01,0,1.000000e-07,1.000000e-07,0,1.000000e-07,4.392603e-01,0,1.000000e-07,2.997936e-02,0,1.000000e-07,6.661487e-02,0,1.000000e-07,1.000000e-07,0,0.000000e+00,2.426818e-01,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,...,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.0,0.0,0,0.000000e+00,0.000000e+00,0,0.0,0.0,0,0.000000e+00,0.000000e+00,0,0.000000,0.000000e+00,0,0.000000,0.000000e+00,0,561.305481,1.000000e-07,0,0.000000e+00,0.000000e+00,0,674.389526,1.000000e-07,0,0.000000e+00,0.000000e+00,0,7.894185e+02,1.000000e-07,0,0.000000e+00,0.000000e+00,0,9.044429e+02,1.000000e-07,0,0.000000e+00,0.000000e+00,0,1.017530e+03,1.000000e-07,0,0.000000,0.000000e+00,0,1.132555e+03,1.000000e-07,0,0.000000,0.000000e+00,0,1.203591e+03,1.000000e-07,0,0.000000e+00,0.000000e+00,0,1.260612e+03,1.000000e-07,0,0.000000e+00,0.000000e+00,0,1.375641e+03,1.000000e-07,0,0.000000e+00,0.000000e+00,0,1.489688e+03,1.000000e-07,0,0.000000e+00,0.000000e+00,0,1.626744e+03,8.138710e+02,0,0.000000e+00,0.000000e+00,0,1.000000e-07,8.783990e+02,0,0.000000e+00,0.000000e+00,0,1.000000e-07,9.139143e+02,0,0.000000e+00,0.000000e+00,0,1.000000e-07,9.709344e+02,0,0.000000e+00,0.000000e+00,0,1.000000e-07,1.006453e+03,0,0.000000e+00,0.000000e+00,0,1.000000e-07,1.062997e+03,0,0.000000e+00,0.000000e+00,0,1.000000e-07,1.098515e+03,0,0.000000e+00,0.000000e+00,0,1.000000e-07,1.142030e+03,0,1.000000e-07,1.139515e+03,0,1.000000e-07,1.206554e+03,0,1.000000e-07,1.189042e+03,0,1.000000e-07,1.263097e+03,0,1.000000e-07,1.000000e-07,0,0.000000e+00,1.312628e+03,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,2537.260926
2,2,Lumos_RSLC8_steppedHCD_SEC_F2,4,4203.118,KQVSDGVAHIHASFNNTIVTITDR(1)-EYGIKNLEVMVK(5),DSSO,4.684720e-13,False,21109,KQVSDGVAHIHASFNNTIVTITDR,EYGIKNLEVMVK,1,5,24,12,K[UNIMOD:1896]QVSDGVAHIHASFNNTIVTITDR,EYGIK[UNIMOD:1896]NLEVMVK,120.0000-2000.0000,67.148304,FTMS,HCD,4.458729e-01,1.000000e-07,0,1.000000e-07,1.000000e-07,0,2.914985e-02,1.000000e-07,0,7.202395e-01,1.000000e-07,0,1.956594e-01,1.000000e-07,0,3.161781e-01,1.000000e-07,0,1.092679e-01,1.000000e-07,0,4.131427e-02,1.000000e-07,0,6.601025e-01,1.000000e-07,0,8.615765e-02,1.000000e-07,0,4.655310e-01,1.000000e-07,0,1.000000e-07,1.000000e-07,0,2.748235e-01,1.000000e-07,0,5.427435e-02,1.000000e-07,0,1.612113e-01,1.000000e-07,0,6.542300e-02,1.000000e-07,0,1.196930e-01,1.000000e-07,0,1.324121e-01,1.000000e-07,0,2.308213e-01,1.000000e-07,0,1.629167e-01,2.891878e-02,0,1.992370e-01,1.000000e-07,0,8.808013e-02,1.138450e-01,0,5.539167e-01,1.000000e-07,0,4.983997e-02,1.185194e-01,0,5.354453e-01,1.000000e-07,0,1.000000e-07,4.045908e-02,0,6.212198e-01,2.538255e-01,0,1.000000e-07,3.600005e-02,0,2.229244e-01,8.827980e-02,0,1.000000e-07,1.238908e-01,0,6.623907e-02,2.642913e-01,0,1.000000e-07,1.000000e-07,0,5.217110e-02,2.310151e-01,0,1.000000e-07,9.450810e-02,0,1.000000e-07,4.655011e-02,0,1.000000e-07,7.199020e-02,0,1.000000e-07,5.903536e-01,0,1.000000e-07,7.297116e-02,0,1.000000e-07,1.577913e-01,0,1.000000e-07,2.968428e-02,0,1.000000e-07,9.269130e-01,0,1.000000e-07,1.000000e-07,0,1.000000e-07,1.000000e+00,0,1.000000e-07,1.000000e-07,0,1.000000e-07,5.855940e-02,0,1.000000e-07,8.940771e-02,0,0.000000e+00,1.877701e+00,0,0.000000e+00,5.699051e-02,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,...,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.0,0.0,0,1.000000e-07,1.000000e-07,0,0.0,0.0,0,3.431432e+02,1.000000e-07,0,0.000000,0.000000e+00,0,442.211090,1.000000e-07,0,0.000000,0.000000e+00,0,1.000000e-07,1.000000e-07,0,0.000000,0.000000e+00,0,6.442716e+02,1.000000e-07,0,0.000000e+00,0.000000e+00,0,1.000000e-07,1.000000e-07,0,0.000000e+00,0.000000e+00,0,1.000000e-07,1.000000e-07,0,0.000000e+00,0.000000e+00,0,871.393616,1.000000e-07,0,0.000000e+00,0.000000e+00,0,1008.453003,1.000000e-07,0,0.000000e+00,0.000000e+00,0,1.121540e+03,1.000000e-07,0,0.000000e+00,0.000000e+00,0,1.258594e+03,6.298009e+02,0,0.000000e+00,0.000000e+00,0,1.329641e+03,6.653220e+02,0,0.000000e+00,0.000000e+00,0,1.000000e-07,1.000000e-07,0,0.000000e+00,0.000000e+00,0,1.000000e-07,1.000000e-07,0,0.000000e+00,0.000000e+00,0,1.000000e-07,1.000000e-07,0,0.000000e+00,0.000000e+00,0,1.000000e-07,1.000000e-07,0,0.000000e+00,0.000000e+00,0,1.000000e-07,1.000000e-07,0,0.000000e+00,0.000000e+00,0,1.000000e-07,1.003489e+03,0,0.000000e+00,0.000000e+00,0,1.000000e-07,1.000000e-07,0,0.000000e+00,0.000000e+00,0,1.000000e-07,1.000000e-07,0,0.000000e+00,0.000000e+00,0,1.000000e-07,1.160080e+03,0,0.000000e+00,0.000000e+00,0,1.000000e-07,1.000000e-07,0,0.000000e+00,0.000000e+00,0,1.000000e-07,1.000000e-07,0,0.000000e+00,1.355174e+03,0,0.000000e+00,1.346168e+03,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,2622.351414
3,3,Lumos_RSLC8_steppedHCD_SEC_F2,4,3299.801,HAVIALTSIYGVGKTR(14)-SKAILAAAGIAEDVK(2),DSSO,2.055504e-12,False,20217,HAVIALTSIYGVGKTR,SKAILAAAGIAEDVK,14,2,16,15,HAVIALTSIYGVGK[UNIMOD:1896]TR,SK[UNIMOD:1896]AILAAAGIAEDVK,120.0000-2000.0000,64.763194,FTMS,HCD,1.553676e-01,1.000000e-07,0,1.000000e-07,1.000000e-07,0,3.607047e-01,1.000000e-07,0,1.000000e+00,1.000000e-07,0,8.891165e-02,1.000000e-07,0,6.848639e-01,1.000000e-07,0,3.699759e-01,1.000000e-07,0,4.731197e-01,1.000000e-07,0,1.069154e-01,1.000000e-07,0,5.752891e-01,1.000000e-07,0,4.127580e-01,1.000000e-07,0,5.357853e-01,1.000000e-07,0,5.456115e-01,1.000000e-07,0,3.293672e-01,4.055484e-02,0,1.969766e-01,1.000000e-07,0,2.905265e-01,1.000000e-07,0,2.100698e-01,1.000000e-07,0,2.402114e-01,4.355974e-02,0,3.146528e-01,1.000000e-07,0,2.673084e-01,6.979369e-02,0,1.922512e-01,1.000000e-07,0,2.116106e-01,1.025189e-01,0,2.375694e-01,1.000000e-07,0,2.349532e-01,5.826683e-02,0,2.220670e-01,1.000000e-07,0,1.000000e-07,1.000000e-07,0,1.621879e-01,1.000000e-07,0,2.986385e-01,1.000000e-07,0,5.770705e-02,1.000000e-07,0,1.642399e-01,1.000000e-07,0,6.922148e-02,2.538819e+00,0,0.000000e+00,1.393831e-01,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,...,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.0,0.0,0,0.000000e+00,0.000000e+00,0,0.0,0.0,0,0.000000e+00,0.000000e+00,0,490.249115,1.000000e-07,0,0.000000,0.000000e+00,0,547.264648,1.000000e-07,0,0.000000e+00,0.000000e+00,0,646.336060,1.000000e-07,0,0.000000e+00,0.000000e+00,0,7.033533e+02,1.000000e-07,0,0.000000e+00,0.000000e+00,0,8.664152e+02,1.000000e-07,0,0.000000e+00,0.000000e+00,0,9.795041e+02,4.902491e+02,0,0.000000,0.000000e+00,0,1.066536e+03,1.000000e-07,0,0.000000,0.000000e+00,0,1.167584e+03,1.000000e-07,0,0.000000e+00,0.000000e+00,0,1.280668e+03,1.000000e-07,0,0.000000e+00,0.000000e+00,0,1.351701e+03,1.000000e-07,0,0.000000e+00,0.000000e+00,0,1.464792e+03,1.000000e-07,0,0.000000e+00,0.000000e+00,0,1.563847e+03,1.000000e-07,0,1.000000e-07,1.000000e-07,0,1.000000e-07,1.000000e-07,0,1.000000e-07,1.000000e-07,0,0.000000e+00,8.864789e+02,0,0.000000e+00,8.774737e+02,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,1684.962442

In [24]:
import logging
import re
from abc import abstractmethod
from pathlib import Path
from typing import Optional, Union

import pandas as pd

from spectrum_io.file import csv

logger = logging.getLogger(__name__)


def filter_valid_prosit_sequences(df: pd.DataFrame) -> pd.DataFrame:
    """
    Filter valid Prosit sequences.

    :param df: df to filter
    :return: df after filtering out unsupported peptides
    """
    logger.info(f"#sequences before filtering for valid prosit sequences: {len(df.index)}")
    # retain only peptides that fall within [7, 30] length supported by Prosit
    df = df[(df["PEPTIDE_LENGTH"] <= 30) & (df["PEPTIDE_LENGTH"] >= 7)]
    # remove unsupported mods to exclude
    unsupported_mods = ["Acetyl (Protein N-term)", "ac"]
    exclude_mods_pattern = re.compile("|".join(map(re.escape, unsupported_mods)))
    df = df[~df["MODIFIED_SEQUENCE"].str.contains(exclude_mods_pattern)]
    # remove non-canonical aas
    df = df[(~df["SEQUENCE"].str.contains("U|O"))]
    # remove precursor charges greater than 6
    df = df[df["PRECURSOR_CHARGE"] <= 6]
    logger.info(f"#sequences after filtering for valid prosit sequences: {len(df.index)}")

    return df


class SearchResults:
    """Handle search results from different software."""

    orig_res: pd.DataFrame
    fake_msms: pd.DataFrame

    def __init__(self, path: Union[str, Path]):
        """
        Init Searchresults object.

        :param path: path to file
        """
        if isinstance(path, str):
            path = Path(path)
        self.path = path

    @abstractmethod
    def read_result(self, path: Union[str, Path], tmt_labeled: str):
        """Read result."""
        raise NotImplementedError

    def generate_internal(self, tmt_labeled: str, out_path: Optional[Union[str, Path]] = None) -> Path:
        """
        Generate df and save to out_path.

        :param out_path: path to output
        :param tmt_labeled: tmt label as str
        :return: path to output file
        """
        if out_path is None:
            out_path = self.path.with_suffix(".prosit")
        if isinstance(out_path, str):
            out_path = Path(out_path)

        if out_path.is_file():
            logger.info(f"Found search results in internal format at {out_path}, skipping conversion")
            return out_path

        df = self.read_result(self.path, tmt_labeled)
        csv.write_file(df, out_path)

        return out_path

    def read_internal(self, path: Union[str, Path]) -> pd.DataFrame:
        """
        Read file from path.

        :param path: path to file
        :return: dataframe after reading the file
        """
        return csv.read_file(path)





import logging
import re
import pandas as pd
import spectrum_fundamentals.constants as c
#from .search_results import SearchResults

#from search_results import SearchResults

logger = logging.getLogger(__name__)

class Plink2(SearchResults):
    """Handle search results from Plink2."""

    @staticmethod
    def read_result(path: str, tmt_labeled: str) -> pd.DataFrame:
        """
        Function to read a csv_file and perform some basic formatting.

        :param path: path to csv_file to read
        :return: pd.DataFrame with the formatted data
        """
        logger.info("Reading csv file")
        columns_to_read = ["Title",
                           "Charge",
                          "Precursor_Mass",
                          "Peptide",
                          "Linker",
                          "Modifications",
                          "Score",
                          "LabelID"] 
        df = pd.read_csv(path, usecols=columns_to_read)
        logger.info("Finished reading csv file")

        # Standardize column names
        df = Plink2.update_columns_for_prosit(df)
        df = Plink2.filter_valid_prosit_sequences(df)
        return df

    def add_mod_sequence(seq_a: str,
                         seq_b: str,
                         mod: str,
                         peptide_a_length: int,
                         crosslinker_position_a: int,
                         crosslinker_position_b: int,
                         crosslinker_type: str):
        """
        Function adds modification in peptide sequence for xl-prosit 
        
        :seq_a: unmodified peptide a
        :seq_b: unmodified peptide b
        :mod: all modifications
        :peptide_a_length: lenght of peptide a
        :crosslinker_position_a: crosslinker position of peptide a
        :crosslinker_position_b: crosslinker position of peptide b
        :crosslinker_type: crosslinker tpe eg. DSSO, DSBU
        :return: modified sequence a and b
        """
        split_seq_a = [x for x in seq_a]
        split_seq_b = [x for x in seq_b]

        for mod in mod.split(";"):
            if mod.startswith("Oxidation"):
                modification = "M[UNIMOD:35]"
                pos_mod = int(mod.split("(")[-1][:-1])
                if peptide_a_length >= pos_mod :
                    split_seq_a[pos_mod-1] = modification
                else:
                    pos_mod = pos_mod - peptide_a_length - 3
                    split_seq_b[pos_mod-1] = modification
                
            elif mod.startswith("Carbamidomethyl"):
                modification = "C[UNIMOD:4]"
                pos_mod = int(mod.split("(")[-1][:-1])
                if pos_mod <= peptide_a_length :
                    split_seq_a[pos_mod-1] = modification
                else:
                    pos_mod = pos_mod - peptide_a_length - 3
                    split_seq_b[pos_mod-1] = modification
            elif mod in ["nan", "null"]:
                break
            else:
                raise AssertionError(f"unknown modification provided:{mod}")
                
        crosslinker_type = crosslinker_type.upper()
        if crosslinker_type == "DSSO":
            split_seq_a[crosslinker_position_a-1] = "K[UNIMOD:1896]"
            split_seq_b[crosslinker_position_b-1] = "K[UNIMOD:1896]"
        elif crosslinker_type in ["DSBU", "BUURBU"]:
            split_seq_a[crosslinker_position_a-1] = "K[UNIMOD:1884]"
            split_seq_b[crosslinker_position_b-1] = "K[UNIMOD:1884]"
        elif crosslinker_type in ["nan", "null"]:
            split_seq_a == split_seq_a
            split_seq_b == split_seq_b                    
        else:
            raise AssertionError(f"unknown crosslinker for xl-prosit:{crosslinker_type}")

        seq_mod_a = ''.join(split_seq_a)    
        seq_mod_b = ''.join(split_seq_b)      

        return seq_mod_a, seq_mod_b


    @staticmethod
    def update_columns_for_prosit(df: pd.DataFrame) -> pd.DataFrame:
        """
        Update columns of df to work with Prosit.

        :param df: df to modify
        :return: modified df as pd.DataFrame
        """
        df.rename(columns={"Title": "RAW_FILE", 
                           "Precursor_Mass": "MASS", #Experimental Mass of crosslinked peptides
                           "Charge": "PRECURSOR_CHARGE",
                           "Linker": "CROSSLINKER_TYPE",
                           "Score":"SCORE",
                           "LabelID": "REVERSE"},
                             inplace=True)
        
        df['SCAN_NUMBER'] = df['RAW_FILE'].str.split('.').str[1]
        df['RAW_FILE'] = df['RAW_FILE'].str.split('.').str[0]
        

        logger.info("Converting Plink2 peptide sequence to internal format")
        df['SEQUENCE_A'] = df['Peptide'].apply(lambda x: re.split(r'[\(\)-]', x)[0])
        df['SEQUENCE_B'] = df['Peptide'].apply(lambda x: re.split(r'[\(\)-]', x)[3])
        df['CROSSLINKER_POSITION_A'] = df['Peptide'].apply(lambda x: re.split(r'[\(\)-]', x)[1])
        df['CROSSLINKER_POSITION_B'] = df['Peptide'].apply(lambda x: re.split(r'[\(\)-]', x)[4])

        df["PEPTIDE_LENGTH_A"] = df['SEQUENCE_A'].apply(len) 
        df["PEPTIDE_LENGTH_B"] = df['SEQUENCE_B'].apply(len)

        df['Modifications'] = df['Modifications'].astype('str') 
        df['CROSSLINKER_POSITION_A'] = df['CROSSLINKER_POSITION_A'].astype('int')
        df['CROSSLINKER_POSITION_B'] = df['CROSSLINKER_POSITION_B'].astype('int')
            
        logger.info("Converting Plink2 peptide sequence to internal format")
        df[['MODIFIED_SEQUENCE_A','MODIFIED_SEQUENCE_B']] = df.apply(lambda row: Plink2.add_mod_sequence(row['SEQUENCE_A'], 
                                                                                 row['SEQUENCE_B'],
                                                                                 row['Modifications'],
                                                                                 row['PEPTIDE_LENGTH_A'],
                                                                                 row['CROSSLINKER_POSITION_A'],
                                                                                 row['CROSSLINKER_POSITION_B'],
                                                                                 row["CROSSLINKER_TYPE"]), axis=1, result_type='expand')
        
        #df["REVERSE"].fillna(False, inplace=True)
        df["REVERSE"].replace(1, False, inplace=True)
        
        df.drop(columns=["Modifications"], inplace=True)
        #print(df.index)
        #display(df)
        #print()
        #df = df.drop(columns=["Modifications"], inplace=True)

        return df

    @staticmethod
    def filter_valid_prosit_sequences(df: pd.DataFrame) -> pd.DataFrame:
        """
        Filter valid Prosit sequences.

        :param df: df to filter
        :return: df after filtration
        """
        logger.info(f"#sequences before filtering for valid prosit sequences: {len(df.index)}")

        df = df[(df["PEPTIDE_LENGTH_A"] <= 30)]
        df = df[df["PEPTIDE_LENGTH_A"] >= 6]
        df = df[(df["PEPTIDE_LENGTH_B"] <= 30)]
        df = df[df["PEPTIDE_LENGTH_B"] >= 6]
        df = df[(~df["SEQUENCE_A"].str.contains("U"))]
        df = df[(~df["SEQUENCE_B"].str.contains("U"))]
        df = df[df["PRECURSOR_CHARGE"] <= 6]
        logger.info(f"#sequences after filtering for valid prosit sequences: {len(df.index)}")

        return df


Plink2.read_result("/home/mkalhor/wilhelmlab/notebooks/notebooks/msms.csv", "d")

,RAW_FILE,PRECURSOR_CHARGE,MASS,Peptide,CROSSLINKER_TYPE,SCORE,REVERSE,SCAN_NUMBER,SEQUENCE_A,SEQUENCE_B,CROSSLINKER_POSITION_A,CROSSLINKER_POSITION_B,PEPTIDE_LENGTH_A,PEPTIDE_LENGTH_B,MODIFIED_SEQUENCE_A,MODIFIED_SEQUENCE_B
0,Lumos_RSLC8_steppedHCD_SEC_F2,5,4253.060,VEDATLVLSVGDEVEAKFTGVDRK(17)-DEADEKDAIATVNK(6),DSSO,1.408896e-13,False,26371,VEDATLVLSVGDEVEAKFTGVDRK,DEADEKDAIATVNK,17,6,24,14,VEDATLVLSVGDEVEAK[UNIMOD:1896]FTGVDRK,DEADEK[UNIMOD:1896]DAIATVNK
1,Lumos_RSLC8_steppedHCD_SEC_F2,5,4289.155,VLESAIANAEHNDGADIDDLKVTK(21)-KVSQALDILTYTNK(1),DSSO,2.034614e-13,False,21289,VLESAIANAEHNDGADIDDLKVTK,KVSQALDILTYTNK,21,1,24,14,VLESAIANAEHNDGADIDDLK[UNIMOD:1896]VTK,K[UNIMOD:1896]VSQALDILTYTNK
2,Lumos_RSLC8_steppedHCD_SEC_F2,4,4203.118,KQVSDGVAHIHASFNNTIVTITDR(1)-EYGIKNLEVMVK(5),DSSO,4.684720e-13,False,21109,KQVSDGVAHIHASFNNTIVTITDR,EYGIKNLEVMVK,1,5,24,12,K[UNIMOD:1896]QVSDGVAHIHASFNNTIVTITDR,EYGIK[UNIMOD:1896]NLEVMVK
3,Lumos_RSLC8_steppedHCD_SEC_F2,4,3299.801,HAVIALTSIYGVGKTR(14)-SKAILAAAGIAEDVK(2),DSSO,2.055504e-12,False,20217,HAVIALTSIYGVGKTR,SKAILAAAGIAEDVK,14,2,16,15,HAVIALTSIYGVGK[UNIMOD:1896]TR,SK[UNIMOD:1896]AILAAAGIAEDVK
4,Lumos_RSLC8_steppedHCD_SEC_F2,5,4452.176,VEDATLVLSVGDEVEAKFTGVDRK(17)-AKDEADEKDAIATVNK(8),DSSO,2.928883e-12,False,23712,VEDATLVLSVGDEVEAKFTGVDRK,AKDEADEKDAIATVNK,17,8,24,16,VEDATLVLSVGDEVEAK[UNIMOD:1896]FTGVDRK,AKDEADEK[UNIMOD:1896]DAIATVNK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1203,Lumos_RSLC8_steppedHCD_SEC_F2,5,4514.297,QDVPSFRPGDTVEVKVWVVEGSK(15)-VFQTHSPVVDSISVKR(15),DSSO,4.684345e-01,False,27642,QDVPSFRPGDTVEVKVWVVEGSK,VFQTHSPVVDSISVKR,15,15,23,16,QDVPSFRPGDTVEVK[UNIMOD:1896]VWVVEGSK,VFQTHSPVVDSISVK[UNIMOD:1896]R
1204,Lumos_RSLC8_steppedHCD_SEC_F2,5,5016.605,AFLPGSLVDVRPVRDTLHLEGKELEFK(22)-AYEDAETVTGVING...,DSSO,4.751261e-01,False,23235,AFLPGSLVDVRPVRDTLHLEGKELEFK,AYEDAETVTGVINGKVK,22,15,27,17,AFLPGSLVDVRPVRDTLHLEGK[UNIMOD:1896]ELEFK,AYEDAETVTGVINGK[UNIMOD:1896]VK
1205,Lumos_RSLC8_steppedHCD_SEC_F2,5,4667.265,MTESFAQLFEESLKEIETRPGSIVR(14)-DMLKAGVHFGHQTR(4),DSSO,4.373675e-01,False,25584,MTESFAQLFEESLKEIETRPGSIVR,DMLKAGVHFGHQTR,14,4,25,14,MTESFAQLFEESLK[UNIMOD:1896]EIETRPGSIVR,DM[UNIMOD:35]LK[UNIMOD:1896]AGVHFGHQTR
1206,Lumos_RSLC8_steppedHCD_SEC_F2,6,3750.942,VKHPSEIVNVGDEITVK(2)-YRNDKNGIIHTTIGK(5),DSSO,4.406477e-01,False,13650,VKHPSEIVNVGDEITVK,YRNDKNGIIHTTIGK,2,5,17,15,VK[UNIMOD:1896]HPSEIVNVGDEITVK,YRNDK[UNIMOD:1896]NGIIHTTIGK
1207,Lumos_RSLC8_steppedHCD_SEC_F2,5,4507.280,FGVSAAAAVAVAAGPVEAAEEKTEFDVILK(22)-EGVSKDDAEAL...,DSSO,4.991013e-01,False,30327,FGVSAAAAVAVAAGPVEAAEEKTEFDVILK,EGVSKDDAEALKK,22,5,30,13,FGVSAAAAVAVAAGPVEAAEEK[UNIMOD:1896]TEFDVILK,EGVSK[UNIMOD:1896]DDAEALKK